use finut;

insert into finut.quiz(difficulty, question, answer,description) values ("MI", "1금융권은 정부에서 만들어진 ‘상호신용금고법’으로부터 나타난 금융회사가 아니라는 것이다.", "TRUE", "은행 외에는 고금리의 사금융밖에 선택지가 없던 1970 년대, 정부에서 ‘상호신용금고법’을 만들어 사금융을 양성화하기 시작했습니다. 이때부터 나타난 회사들은 특정 그룹이나 분야에 전문성을 가진 회사였습니다. 이렇게 새로운 금융회사들이 만들어지던 시기에, 은행과 은행이 아닌 금융회사를 구별해서 부르기 시작했습니다. 예전부터 있었던 은행을 1 금융권으로, ‘은행이 아닌’ 금융회사를 2금융권으로 부르게 된 거죠. 1금융권인 은행과 2금융권에 속해있는 저축은행의 경우, 예금과 대출을 해준다는 측면에서 비슷한 기능을 하기 때문에 소비자 입장에서는 같은 선상에 두고 비교해볼 만합니다.안정성이 높지만 수익률(이자율)이 낮은 1금융권 예금을 택할지, 대출금리가 높지만 대출받기가 더 쉬운 2금융권 대출을 택할지 비교해보는 거예요.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "추가경정예산안은 이미 1년 예산을 정해두었는데, 예산을 세운 뒤에 생긴 일 때문에 금액을 더 보태서 고친다는 걸 뜻하는 것이다.", "TRUE", "추경은 ‘추가경정예산’의 줄임말이고, 경정(更正)은 ‘바르게 고친다’라는 뜻이에요. 추가경정예산은 이미 1년 예산을 정해두었는데, 예산을 세운 뒤에 생긴 일 때문에 금액을 더 보태서 고친다는 걸 뜻하죠. 연초에 세운 계획보다 돈을 더 쓰겠다는 건데요. 추경안은 자연재해나 큰 사고가 나서 인프라와 사회를 복구해야 할 때 나옵니다. 그래서 지난 추경안 규모를 보면 굵직한 경제적 충격들을 읽을 수 있어요. 추경 규모가 10조 원을 넘는 곳(빨간색 그래프)은 리먼브라더스 사태가 촉발한 세계 금융위기, 브렉시트 등 우리나라뿐만 아니라 세계적인 경제 위기가 있었던 시기입니다. 그중에서도 2020년과 2021년의 추경 횟수와 금액은 ‘역대급’이니, 코로나19가 세계적으로 얼마나 커다란 경제적 충격을 가져왔는지 알 수 있어요. 사실 추경 자체가 엄청나게 특별한 일은 아닙니다. 우리나라뿐만 아니라 전 세계 국가 대부분이 매년 추경을 실시합니다. 돈 쓸 일이 너무 많다 보니 1년 동안 얼마가 필요할지 정확하게 예측하기가 어렵거든요. 돌발사태가 발생하기도 하고요. 국가가 사업을 집행하는 데는 국민의 세금이 사용됩니다. 그래서 국민의 대리인인 국회의원과 정당이 추가예산이 필요하다는 행정부를 상대로 견제하기 시작합니다. ‘추경을 하느냐, 마느냐’보다는 추경 횟수와 액수 등을 두고 다투죠. 일명 ‘감액심사’라고 해요. 정치적 이해관계에 따라 여당이 행정부 편을 많이 들어주기도 하는데요. 보통 매년 추경을 하기 때문에 ‘필요하다’라는 쪽으로 결론이 나긴 합니다. 하지만 모든 추경안이 실행되는 건 아니에요. 예를 들어 어떤 정당이 추경을 해야 할 만큼 꼭 필요한 사업이라고 생각하지 않고, 이들의 주장이 국회 다수결로 지지를 받는다면 추경안은 실행되지 않습니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "2차전지는 충전과 방전을 통해 사용이 가능한 전지가 아니에요.", "FALSE", "2차전지는 충전과 방전을 통해 여러 번 사용이 가능한 전지예요. 대표적인 2 차전지로는 휴대폰 배터리가 있습니다. 종류는 납 축전지, 니켈카드뮴 전지, 니켈수소 전지, 리튬이온 전지 등이 있어요.");
insert into finut.quiz(difficulty, question, answer, description) values ("MI", "52주 신고가는 특정 주식이 지난 1년 동안 기록한 가장 높은 주가입니다.", "TRUE", "52주 신고가는 특정 주식이 지난 52주(1년) 동안 기록한 가장 높은 주가를 말해요.");
insert into finut.quiz(difficulty, question, answer, description) values ("LO", "52주 신저가는 특정 주식이 지난 52주(1년) 동안 기록한 가장 낮은 주가를 말합니다.", "TRUE", "52주 신저가는 특정 주식이 지난 52주(1년) 동안 기록한 가장 낮은 주가를 말해요.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "bp(베이시스포인트)는 0.01%p의 움직임도 금융시장에 큰 영향을 미칩니다.", "TRUE", "기준금리 뉴스에 자주 등장하는 ‘bp’는 ‘basis point’의 약자예요. 금융에서 쓰이는 기본단위로, 금리나 수익률, 환율을 나타낼 때 사용합니다. 일반적으로 사용하는 백분율이 아닌 ‘만분율’ 단위의 움직임을 표현하는데요. 1bp는 0.01%p, 10bp는 0.1%p, 100bp는 1%p예요. 금융시장에서는 0.01%p의 움직임도 영향력이 커요. 그래서 0.01%p도 뉴스에 자주 언급됩니다. 백분율을 기준으로 ‘퍼센트포인트’라고 말하는 것보다 만분율을 기준으로 bp로 나타내는 것이 정보전달에 더 효율적이라서 사용한다는 얘기가 있어요.");
insert into finut.quiz(difficulty, question, answer, description) values ("MI", "DSR은 내 소득 대비 금융부채 원리금 상환비율로, 40%를 넘는 경우에는 대출을 해주지 않는다.", "TRUE", "DSR(Debt Service Ratio)은 내 소득 대비 금융부채 원리금 상환비율이에요. DSR 40%라면 내 연 소득이 1억 원일 때, 1년 동안의 원금과 이자 상환비율이 4천만 원을 넘지 않는 정도까지 대출을 해준다는 뜻이에요.");
insert into finut.quiz(difficulty, question, answer, description) values ("LO", "DTI(총부채상환비율)는 연 소득 대비 금융비용 부담률을 나타내는 지표입니다.", "TRUE", "DTI(Debt to Income : 총부채상환비율)는 연 소득 대비 금융비용 부담률을 의미합니다. 소득과 비교한 대출금 수준을 판단하는 지표예요. DTI는 ‘나의 연소 득’에서 ‘주택담보대출의 원금 상환과 이자, 다른 대출의 이자로 나가는 금액’이 차지하는 비중으로 구합니다. 내가 가진 모든 대출의 원리금 상환금액을 합쳐 따지는 DSR보다는 유한 기준입니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "ESG는 환경, 사회, CORPORATE GOVERNANCE에 대한 고려를 의미합니다.", "TRUE", "ESG는 Environmental(환경), Social(사회), Governance(지배구조)의 첫 글자를 조합한 단어로 기업의 친환경 경영, 사회적 책임, 투명한 지배구조 등을 의미합니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("MI", "ETF는 특정 주식에 대한 투자 상품이 아니다.", "TRUE", "ETF(Exchange Traded Fund)는 말 그대로 인덱스펀드를 거래소에 상장시켜 투자자들이 주식처럼 편리하게 거래할 수 있도록 만든 상품입니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("LO", "G7은 매년 정기적으로 국제 사회 현안에 대한 회의를 개최하는 7개국을 의미합니다.", "TRUE", "G7. Group of Seven Summit. 주요 7개국 정상회담의 약자입니다. 미국, 캐나다, 영국, 독일, 프랑스, 이탈리아, 일본 7개국은 매년 정기적으로 국제 사회 현안에 대한 회의를 개최해요. 이 회담뿐만 아니라 이 회담에 참여하는 7개국을 G7이라고 줄여 부르기도 해요.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "GNI는 일정 기간 내 ‘우리나라 국적을 가진 사람’이 벌어들인 모든 소득을 더한 것이다.", "TRUE", "GNI는 Gross National Income의 약자로, ‘국민총소득’입니다. GNI는 일정 기간 내 ‘우리나라 국적을 가진 사람’이 벌어들인 모든 소득을 더한 거예요. 우리나라에 거주하고 있는 외국인의 소득은 제외하고, 외국에 거주하는 우리나라 국민의 소득을 포함해요. GNI를 구하는 가장 큰 이유는 국가가 아니라 국민들의 생활 수준을 알아보기 위해서예요. GNI와 유사한 지표로는 GDP가 있어요.");
insert into finut.quiz(difficulty, question, answer, description) values ("MI", "GVC 후방참여율은 해외에서 수입한 중간재를 이용해 상품을 생산하고, 이를 다시 수출하는 방식으로 진행되는 것이다.", "TRUE", "GVC 후방참여율은 해외에서 수입한 중간재를 이용해 상품을 생산하고, 이를 다시 수출하는 비율을 말해요. 이 수치가 높은 나라일수록 전 세계 자원이 거쳐가는 글로벌 생산기지라 할 수 있어요.");
insert into finut.quiz(difficulty, question, answer, description) values ("LO", "LTV는 주택담보대출의 대출가능금액을 산출할 때 사용되는 공식입니다.", "TRUE", "LTV는 주택담보대출비율(Loan to Value ratio)입니다. 공식은 ‘(대출한 금액) / (아파트 가치)*100’이에요. 즉, 총 아파트 가치에 비교한 대출금의 비중을 보여줘요.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "M&A(인수합병)는 기업이 다른 기업의 경영권을 획득하고자 하는 인수와 다른 기업의 소유권을 획득하고자 하는 합병을 합한 개념입니다.", "TRUE", "M&A는 ‘Merger(합병)&Accquisition(인수)’의 약자로, 인수와 합병을 통해 회사 규모를 키우거나 시장에서 빠르게 경쟁력을 키우는 것이 목적이에요.");
insert into finut.quiz(difficulty, question, answer, description) values ("LO", "PMI ‘ISM 제조업 구매관리자지수’는 생산 관련 지수가 아니고, 경제동향지표입니다.", "TRUE", "PMI 지수는 미국의 공급관리협회에서 매달 조사하는 경기동향지표로, 제조업 실무자에게 업황을 묻는 방식으로 업계 전망을 직접적으로 파악할 수 있어요.");
insert into finut.quiz(difficulty, question, answer, description) values ("MI", "가처분소득은 내가 번 소득에서 세금이나 보험료 등 필수로 나가는 지출을 제외하고, 정부의 혜택 등을 더한 금액입니다.", "TRUE", "가처분소득은 내가 번 소득 중 소비와 저축으로 쓸 수 있는 돈을 뜻해요. 구체적으로는 내가 번 돈에서 세금이나 보험료 등 필수로 나가는 지출을 제외하고, 정부의 혜택 등을 더한 금액입니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "감사보고서는 외부 감사인이 회사의 재무제표를 보고, 제대로 작성되었는지 확인하고 의견을 표명하는 보고서입니다.", "TRUE", "감사보고서는 외부 감사인이 회사의 재무제표를 보고, 제대로 작성되었는지 확인하고 의견을 표명하는 보고서입니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("LO", "개인소비지출(PCE)은 개인이 소유한 재산을 사용하여 구입하는 모든 물품과 서비스를 의미합니다.", "TRUE", "개인소비지출(Personal Consumption Expenditures, PCE)은 가계가 재화와 서비스를 구매하는 데 사용하는 지출을 의미합니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("MI", "거래대금은 주식이 사고 팔린 총 금액으로, 매매된 주식의 수량을 나타내는 거래량과 함께 보는 지표입니다.", "TRUE", "거래대금은 주식이 사고 팔린 총 금액입니다. 매매된 주식의 수량을 나타내는 거래량과 함께 보는 지표입니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("HI", "경기순환사이클은 상승과 하락을 반복하는 현상을 의미하며, 크게 회복기-활황기- 후퇴기-침체기가 있다.", "TRUE", "경기가 일정 주기를 두고 상승과 하락을 반복하는 현상을 경기순환이라고 합니다.");
insert into finut.quiz(difficulty, question, answer, description) values ("MI", "경상수지는 일정 기간 우리나라와 외국 사이 상품·서비스의 수출입과 노동·자본에 지급된 대가처럼 경제에서 ‘생산을 담당하는 요소’의 흐름을 금액으로 계산한 장부입니다.", "TRUE", "경상수지는 일정 기간 우리나라와 외국 사이 상품·서비스의 수출입과 노동· 자본에 지급된 대가처럼 경제에서 ‘생산을 담당하는 요소’의 흐름을 금액으로 계산한 장부라고 할 수 있어요.");
insert into finut.quiz(difficulty, question, answer, description) values ("LO", "경착륙은 호황이 끝나고 자산 가치가 폭락하고 실업자가 급증하는 사태를 말합니다.", "TRUE", "경착륙은 활발하게 잘 나가던 경기가 얼어붙으면서 자산 가치가 폭락하고 실업자가 급증하는 사태를 말합니다. 연착륙과 대비되는 개념입니다.");


select * from quiz;